### ISSUE TITLE
ApprovalUtilities.Net45 is not published to nuget.org

### ISSUE THREAD

**Issue by jamesrcounts** [approvals/ApprovalTests.Net#111]
It is only available on the CI server.  It needs to be added to the nuget build/push script

**Comment by goblinfactory** [comment]
Given that this is the only open "bug" for approvalTests it would be good to know if  this issue still open? Especially since this was created 16 Feb 2015? @isidore Can this issue be closed?

**Comment by isidore** [comment]
Yeah, approvalutilities is 4.5 now anyways.
