### ISSUE TITLE
Add support for xunit 2.0

### ISSUE THREAD

**Issue by niemyjski** [approvals/ApprovalTests.Net#112]
I just upgraded to xunit 2.0 and my approvals tests are failing:

```
System.Exception

Could Not Detect Test Framework



Either:

1) Optimizer Inlined Test Methods



Solutions:

a) Add [MethodImpl(MethodImplOptions.NoInlining)]

b) Set Build->Opitmize Code to False 

   & Build->Advanced->DebugInfo to Full



or

2) Approvals is not set up to use your test framework.

It currently supports [NUnit, MsTest, MbUnit, xUnit.net, xUnit.extensions, Machine.Specifications (MSpec)]



Solution:

To add one use ApprovalTests.Namers.StackTraceParsers.StackTraceParser.AddParser() method to add implementation of ApprovalTests.Namers.StackTraceParsers.IStackTraceParser with support for your testing framework.

To learn how to implement one see http://blog.approvaltests.com/2012/01/creating-namers.html
   at ApprovalTests.Namers.StackTraceParsers.StackTraceParser.Parse(StackTrace stackTrace)
   at ApprovalTests.Namers.UnitTestFrameworkNamer..ctor()
   at ApprovalTests.Approvals.<.cctor>b__c()
   at ApprovalTests.Approvals.GetDefaultNamer()
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
   at Exceptionless.Api.Tests.Utility.ApprovalsUtility.VerifyFile(String approvedFilePath, Object receivedData) in Approvals.cs: line 10
```

**Comment by niemyjski** [comment]
I believe the culprit is: https://github.com/approvals/ApprovalTests.Net/blob/master/ApprovalTests/Reporters/XUnitReporter.cs#L10

**Comment by niemyjski** [comment]
As per their [release notes](http://xunit.github.io/release-notes/2015-03-16.html)

Separated Assertions. A common theme among xUnit.net users was that they wanted the ability to choose assertion libraries other than ours. In 2.0, we have separated the core framework from the assertion library, and we offer the asserts in either binary or source form. By bringing in assertions as source, you can extend the Assert class itself with your own assertion methods.

**Comment by niemyjski** [comment]
Do you have any ideas on this issue?

**Comment by jamesrcounts** [comment]
You are probably right about where the problem is coming from, but I haven’t had a chance to test. yet.  I may be able to this weekend.  Out of curiosity, are you using the latest release, or are you using the latest CI build from myget.org?

**Comment by niemyjski** [comment]
Latest release from Nuget

**Comment by niemyjski** [comment]
+1

**Comment by niemyjski** [comment]
@isidore any chance you could take a look into this? There is a pull request out there for this.

**Comment by niemyjski** [comment]
@isidore You've accepted the pull request for this, can you please push out a release?

**Comment by niemyjski** [comment]
It's been a few months since this was reported and fixed... Can we please get a release out for this.

**Comment by robdmoore** [comment]
+1

**Comment by niemyjski** [comment]
Hey guys, I know that this task has been completed but it's not pushed out via nuget.. I'm about to rip out this functionality from my tests as I need xunit 2.0..

**Comment by togakangaroo** [comment]
Stauts update?

**Comment by jamesrcounts** [comment]
This was released to nuget a couple months ago.

**Comment by togakangaroo** [comment]
:) thanks
