### ISSUE TITLE
Incorrect behavior in parallelized xUnit

### ISSUE THREAD

**Issue by hatboyzero** [approvals/ApprovalTests.Net#114]
With the advent of xUnit 2.0.0, it looks like the new support for parallelized test execution has exposed a race condition in ApprovalTests.  When running a collection of tests distributed amongst multiple test classes, I experience seeing output for one test being written as the received output for an entirely different test.

**Comment by jamesrcounts** [comment]
As a work around, parallel execution can be disabled: `[assembly: CollectionBehavior(DisableTestParallelization = true)]`

**Comment by SimonCropp** [comment]
the current version corrects support async and parallelized test. if you can still repro an issue please share a minimal solution that illustrates the problem
