### ISSUE TITLE
Start KDiff in merge mode not diff mode

### ISSUE THREAD

**Issue by JakeGinnivan** [approvals/ApprovalTests.Net#115]
When making a change which affects a lot of approval tests it would save a lot of time if KDiff (not sure about what others do) started in merge mode not diff mode?

**Comment by tekmaven** [comment]
:+1:

**Comment by jamesrcounts** [comment]
Probably makes sense just to create a second reporter that works this way so that those that want it can choose it.

**Comment by isidore** [comment]
agreed that this would be good, how do you it? (what's the command line to open in merge)

**Comment by isidore** [comment]
done in 8a353a4
