### ISSUE TITLE
Report instance type not DeclaringType in stackframeparser

### ISSUE THREAD

**Issue by JakeGinnivan** [approvals/ApprovalTests.Net#116]
Looking into this it is not a simple change, but I have a few projects where this would be handy and wanted to start a discussion.
## Scenario

In shouldly, I have a base class which enforces the 2 different checks for each Should\* method. It makes it really easy to just create a new class and implement the two abstract members and the actual test methods are in the base class. I did not use approval tests for this because different scenarios overwrite each others approved files and it is a bit of a pain to implement a custom namer etc.
## Implementation

I think the simplest way is to just do a string replace. This is what I have done:

``` csharp
public class DerivedClassUnitTestFrameworkNamer : UnitTestFrameworkNamer
{
    private readonly object instance;

    public DerivedClassUnitTestFrameworkNamer(object instance)
    {
        this.instance = instance;
    }

    public override string Name
    {
        get
        {
            var traceParser = new StackTraceParser();
            traceParser.Parse(Approvals.CurrentCaller.StackTrace);
            return base.Name.Replace(traceParser.ApprovalName, instance.GetType().Name);
        }
    }
}
```

This could be pushed down into the UnitTestFrameworkNamer so I don't need to parse the stack trace twice. 
It would also be handy to have a `Approvals.Verify(<whatever>, IApprovalNamer namer)` overloads as well to make it easy to specify namers. The usage would then be `Approvals.Verify(text, new UnitTestFrameworkNamer(this))`

Thoughts?

**Comment by SimonCropp** [comment]
@JakeGinnivan given this was 5 years i assume u have on. so will close. please let us know if u still need this
