### ISSUE TITLE
BeyondCompare 4 is not supported by the BeyondCompareReporter

### ISSUE THREAD

**Issue by pullrich** [approvals/ApprovalTests.Net#118]
Output message:
System.Exception: Could not find BeyondCompare at C:\Program Files\Beyond Compare 3\BCompare.exe, please install it

It is available at:
"C:\Program Files (x86)\Beyond Compare 4\BCompare.exe"
Version: 4.0.7.19761

ApprovalTest Version: 3.0.8

**Comment by jamesrcounts** [comment]
Support for Beyond Compare 4 was added in 9dd395e00ee2a9fddc097ce3dfbf0ab6becd49a3 and is currently only available in the CI pre-release build.

https://www.myget.org/gallery/approvaltests

**Comment by jeremysimmons** [comment]
works in https://www.nuget.org/packages/ApprovalTests/3.0.11. vote to close as fixed.
