### ISSUE TITLE
AppVeyor reporter

### ISSUE THREAD

**Issue by JakeGinnivan** [approvals/ApprovalTests.Net#135]
Need to create a reporter for AppVeyor

**Comment by jamesrcounts** [comment]
Looks like you can just check if [APPVEYOR](http://www.appveyor.com/docs/environment-variables) is true in the environment, and then the implementation should be pretty much the same as [GoContinuousDeliveryReporter](https://github.com/approvals/ApprovalTests.Net/blob/2ea22b074200fa762f277974ae15cf5073fe9fb2/ApprovalTests/Reporters/GoContinuousDeliveryReporter.cs).

**Comment by JakeGinnivan** [comment]
Yep, I just created it after a conversation with Llewellyn. I don't have time atm so just adding to track it

Sent from my Windows Phone
________________________________

**Comment by niemyjski** [comment]
I need this as well!!!! I'd also like to turn off all the reporting in appveyor as it's really noisey

**Comment by jamesrcounts** [comment]
Added in 159a8da5cf4b43657aa5b5acc64cf42f2ba5dc60

**Comment by niemyjski** [comment]
Any idea when this will be deployed?

Sent from Outlook Mobile




On Wed, Jan 13, 2016 at 1:08 PM -0800, "Jim Counts" <notifications@github.com> wrote:












Closed #135.

**Comment by jamesrcounts** [comment]
Nope
