### ISSUE TITLE
Support Data Driven Tests

### ISSUE THREAD

**Issue by codecounselor** [approvals/ApprovalTests.Net#138]
I attempted to use Approvals inside of a test method that is using the [MSTest support for data driven tests](https://msdn.microsoft.com/en-us/library/ms182527.aspx).

The outcome is that there is only a single approved/received pair no matter how many instances of the test are run.  In my simple test scenario I had two.  The framework creates test results for row0, row1, etc.  

The request here would be to somehow support an approved output per row of input.

I'm willing to submit a pull request if someone can guide me in the right direction.

**Comment by jamesrcounts** [comment]
the current support for this is discussed here #137

**Comment by codecounselor** [comment]
Thanks for the quick response, for some reason this didn't show up in my search.  Perfect timing!
