### ISSUE TITLE
Ignoring DateTimeStamp in the xml result

### ISSUE THREAD

**Issue by aadil79** [approvals/ApprovalTests.Net#139]
Hello I wanted to use approval .net to verify some soap responses we get back from our services.
In my example we have  a  Modified Date field that can change based on any updates that happened to the corresponding record in the database.However I wanted a way for specifying certain fields to be ignored in terms of the comparison(or check only for not null instead of the exact value).
Is there a way to do it today or any hooks i can extend for my use cases.

**Comment by aadil79** [comment]
I created a sanitizer to scrub the result of fields i don't care and then pass it to the approval tests verification(approved xml with corresponding empty tags) to move forward.

**Comment by isidore** [comment]
Yes that's the right approach, should we add some basic scrubbers to make that easier?

Llewellyn Falco

**Comment by aadil79** [comment]
sure, that would be helpful.Let me know if I can help in any way.
