### ISSUE TITLE
Exception - "Could not find the Field for this MSpec Test"

### ISSUE THREAD

**Issue by libbyrobinson** [approvals/ApprovalTests.Net#146]
Just upgraded to VS2015 and R#10. Running existing tests via the R# MSpec test runner, approval tests are failing.

![image](https://cloud.githubusercontent.com/assets/791832/13583613/397c3078-e467-11e5-8f4c-d7d9b240262b.png)

**Comment by SimonCropp** [comment]
sorry about the much delayed response. i am assuming this is fixed now. if not can you share a small solution that reproduces this issue?
