### ISSUE TITLE
Can the golden-file be placed inside the source?

### ISSUE THREAD

**Issue by kasajian** [approvals/ApprovalTests.Net#153]
I worked with a similar system to ApprovalTests where the "expected result" data that ApprovalTests stores in a text file, are stored right in the unit-test itself, in a multi-line @"" C# string.

I realize this has disadvantages, but it also has an advantages:
- If the unit test moves, the "expected result" moves with it.
- You can easily see what the expected result ought to be because it's right there in the source.   You don't have to go to a separate file.

I think in some cases this would be more useful, especially when the expected results are small.   So my question is, has this ever been proposed?  Is there a way to use the existing ApprovalTests system to do this by creating a custom reporter?

**Comment by isidore** [comment]
you don't need a reporter really, you can just do

    var expected = @" your expected here ";
    Assert.AssertEqual(expected, actual);



Llewellyn Falco
www.approvaltests.com

**Comment by kasajian** [comment]
If I do this:
    var expected = @" your expected here ";
    Assert.AssertEqual(expected, actual);

and expected and actual are not the same, I won't see in a diffing utility, which is what I would want.

What I really want is the same that as approval tests, but the "approved" version isn't in a file, but is passed in via the Verify type method.   If the received and approved don't match, then diff utility is run to report the discrepancy.    If the approved version is correct, the user doesn't have to update.   If the approved version is not correct, they would they copy the text received test from diff utilit and paste it into the source code, inside of a literal string.

This is a nice pattern with one problem.   What happens when the data itself has a double-quote in it.   A workaround would be to first paste the data into notepad then search/replace one double-quote with two double-quotes.   However, I found the following technique better: when the utility reports the 'received' text to the differ, it automatically replaces the single double-quote with double-double-quote.   That means, if the Received data looks like this
    Joe said, "Hi Jane"
The diff-utility will show the received data as:
    Joe said, ""Hi Jane""

Now when the the user copies the received data, they can paste directly into a C# literal string.

**Comment by jamesrcounts** [comment]
It sounds pretty complicated.  The bottom line is that having the data in text files allows the diff utilities to actually manage those files, and approve the results, cutting, pasting, etc, would be a step backward.  Yes the text files are a pain about 10% of the time, those times when you rename or move a test.  I would love to have a solution to that 10% problem, but rolling everything back to manual cut and paste would degrade the experience 100% of the time.

For me its not worth it but it sounds like your preference goes the other way.

**Comment by isidore** [comment]
What you are looking for is 

    VerifyInFile(String expected, String actual)
    {
        expected = expected.ReplaceAll("""","""""");
        actual = actual.ReplaceAll("""","""""");
        StringReporting.DiffWith(expected, actual);
        Assert.AssertEqual(expected, actual);
    }

But I'm with jim that I don't think I want to add it to the library just yet. Try it out as a separate method for now and maybe we will revisit it later.

**Comment by kasajian** [comment]
I agree with you guys.

I'm proposing something that I've actually used and liked in a different
system -- that's hand-rolled.   So it was quite nice.   I'm new to
ApprovalTests and like it a lot.   I'm using it on a current project
out-of-the-box.

The thing I'm asking for adding actually sounds like a trivial amount of
work -- the question really is, does it makes and belong in this library.
 So I'll just do at the application level and see how it goes.   If I come
up with something I like in the future, that I think others could benefit
from, I'll update this thread.

Thanks guys.

**Comment by SimonCropp** [comment]
this is done https://github.com/approvals/ApprovalTests.Net/blob/master/docs/ApprovalTests/Features.md#approvalsasserttext
