### ISSUE TITLE
How do I automatically approve approval-tests when I run them?

### ISSUE THREAD

**Issue by kasajian** [approvals/ApprovalTests.Net#154]
Use IReporterWithApprovalPower.   See http://stackoverflow.com/questions/37604285/how-do-i-automatically-approve-approval-tests-when-i-run-them

Please add to wiki.

**Comment by SimonCropp** [comment]
as an aside i added this as a first class feature to Verify https://github.com/SimonCropp/Verify#autoverify

**Comment by SimonCropp** [comment]
given @isidore commented on stackoverflow that he thinks this is a bad idea, i will close this one
