### ISSUE TITLE
NullReferenceException calling Verify

### ISSUE THREAD

**Issue by droyad** [approvals/ApprovalTests.Net#155]
When calling `ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)` a `NullReferenceException` is thrown due to `currentCaller.Value` being null.

Workaround: Call `Approvals.SetCaller();` at least once.

**Comment by droyad** [comment]
Looks like there is an open PR that would fix this: https://github.com/approvals/ApprovalTests.Net/pull/141

I'll leave this open till then as I didn't find the related issue first up. Love this library BTW.

**Comment by 304NotModified** [comment]
Could be closed as https://github.com/approvals/ApprovalTests.Net/pull/141 has been merged?
