### ISSUE TITLE
disconnect between sourceforge and github

### ISSUE THREAD

**Issue by SimonCropp** [approvals/ApprovalTests.Net#16]
When i google "approval tests" i get this 

http://approvaltests.sourceforge.net/

which doesnt have a link to this

https://github.com/approvals/ApprovalTests.Net

**Comment by jawn** [comment]
Seems to me this issue can be closed:
I get https://github.com/approvals/ApprovalTests.Net if i'm logged into my google account
or approvaltests.com when I'm in private mode using Chrome.

**Comment by SimonCropp** [comment]
@jawn thanks for the followup
