### ISSUE TITLE
TfsReporter is inefficient by not caching parent process name check

### ISSUE THREAD

**Issue by marcind** [approvals/ApprovalTests.Net#165]
We have a scenario where we have an XUnit v2 Theory test that invokes Approvals.VerifyJson() for multiple test inputs:

``` C#
[Theory]
// Bunch of InlineData etc.
[UseApprovalSubdirectory(ApprovalContractSerializer.Subdirectory)]
[UseReporter(typeof(QuietReporter))]
[MethodImpl(MethodImplOptions.NoInlining)]
public void ContractMatches(Type type)
{
    NamerFactory.AdditionalInformation = ApprovalContractSerializer.GetFriendlyName(type);
    Logger.Writer = new NullWriter();

    var json = ApprovalContractSerializer.SerializeContract(type);

    Approvals.VerifyJson(json);
}
```

These tests end up being slow, because `DefaultFrontLoaderReporter` tries to look up a matching reporter for each execution, and the implementation of `TfsReporter` checks the parent process name every time (instead of caching the result similarly to `MightyMooseAutoTestReporter`).

I can submit a PR to fix this, just wanted to see if you have any contribution guidelines first.

**Comment by jawn** [comment]
@marcind, since we are also using TFS I am curious to know whether this is still an issue?

**Comment by marcind** [comment]
No idea. This was filed years ago. I don't work with TFS anymore.
