### ISSUE TITLE
FileApprover doesn't use ApprovalException's received/approved properties

### ISSUE THREAD

**Issue by flcdrg** [approvals/ApprovalTests.Net#169]
The current implementation of `FileApprover` caches the received and approved values in the `Approve()` method.

If another class extends `FileApprove`r and overrides the `Approve(string,string)` method, it may choose to return an `ApprovalException` result that has different values. However currently those are not used by the `ReportFailure` method - instead it uses the previously set received and approved field values.

I think it would make sense to use `failure.Approved` and `failure.Received` instead of `this.approved`/`this.received`. That should continue to work for normal use, but give more flexibility for when overriding this class.

**Comment by SimonCropp** [comment]
closing this for now. please provide a repro if it is still an issue
