### ISSUE TITLE
Modifying the behaviour of reporters

### ISSUE THREAD

**Issue by flcdrg** [approvals/ApprovalTests.Net#170]
I want to be able to disable or quieten a reporter (the TeamCity one as it happens) for particular tests.

These tests are ones that I know will fail, and so my current test method was catching the ApprovalMismatchException and then using NUnit's Asssert.Inconclusive()

This was working fine in 3.0.11 but trying to upgrade to 3.0.13 it now doesn't work as the recent modification to the reporters is causing them to output the diff and return an AssertException when run on the build server (they run as expected in Visual Studio on my machine).

This is in spite of the fact that I have a [UseReporter] attribute on the test method. That appears to be ignored when the tests are run in TeamCity.

**Comment by SimonCropp** [comment]
closing this one since there is no repro. happy to re open if a repro is provided
