### ISSUE TITLE
VisualStudioProjectFileAdder not working?

### ISSUE THREAD

**Issue by asherber** [approvals/ApprovalTests.Net#176]
I gather that the point of the VisualStudioProjectFileAdder is to automatically add approved files to the project as they are created, but it doesn't seem to be working for me.
```csharp
[TestFixture]
[UseReporter(typeof(VisualStudioReporter), typeof(VisualStudioProjectFileAdder))]
[UseApprovalSubdirectory("Approved")]
public class Class1
{
}
```
I tried both with and without the `UseApprovalSubdirectory` attribute, in case that was throwing things off, but the files never got added.

**Comment by SimonCropp** [comment]
given VS now supports including files by default this would seem redundant?

**Comment by asherber** [comment]
I haven't been working with ApprovalTests lately, but that seems right to me.

**Comment by SimonCropp** [comment]
@asherber thanks for the followup
