### ISSUE TITLE
Configured git diff tool as reporter?

### ISSUE THREAD

**Issue by lars-erik** [approvals/ApprovalTests.Net#183]
I was happy to see Beyond Compare pop as the diff tool without me doing anything specific.
However, I normally use the built-in difftool in Visual Studio.
Would be really nice if the DiffReporter just used whatever is configured in the current git configuration.
No idea whether easy or not, but would be really cool if the diff just opens in the environment I'm developing and running the tests in.
(BC launches dead fast tho, so no biggie)

**Comment by lars-erik** [comment]
I'm a bit stumped. It actually launched the VS difftool on my home-box. It fires BeyondCompare on the work-box. VS should've been default there too. Need to do some digging.

**Comment by 304NotModified** [comment]
Fixed by https://github.com/approvals/ApprovalTests.Net/pull/182 ?

**Comment by lars-erik** [comment]
I finally found the VisualStudioReporter type, and that forces use of VS. I guess it picks VS as default on my home box since I don't have Beyond Compare on it. And I figure the DiffReporter favors BC over VS. I'm closing and shrugging it off as by design.

**Comment by isidore** [comment]
would suggest making a custom reporter of your own to use. here's the code
you'll need ...

 public class LarsReporter : FirstWorkingReporter
{
    public LarsReporter()
        : base(
            VisualStudioReporter.INSTANCE, DiffReporter.INSTANCE)
    {
    }
}

Llewellyn Falco
www.approvaltests.com


On Mon, Mar 13, 2017 at 10:53 AM, Lars-Erik Aabech <notifications@github.com

**Comment by lars-erik** [comment]
I just went with the visual studio reporter, but knowing reporters are that simple to chain is great.
Love the product so far. It sneaks into more and more of my tests nowadays. :)
