### ISSUE TITLE
Suggestion: Inline approvals

### ISSUE THREAD

**Issue by dalpert-korewireless** [approvals/ApprovalTests.Net#189]
A number of times I find myself reaching for ApprovalTests and it's quick awesomeness to quickly visualize and verify a complex object.

Often, however, I wind up using Approvals on relatively small samples, and in those cases it might be nice to have an option to capture the Approved text in a string variable so that it could be easily visualized inline with the test itself rather than hiding small approvals in a separate files.

Some syntax like:

````
       Approvals.Inline(@"
{
  "tags": [
    {"name": "Serenity"},
    {"name": "Firefly"}
  ]}")
         .Verify(actual);
````

That looks awkward so I'm sure we could do better, but the idea would be to allow a test to specify the approved result inline in the test itself, then pass that to the Approvals which might use a different naming strategy to create `approved.txt` and `received.txt` files in the temp folder or `approved.inline.txt` and `received.txt` to flow into the existing reporters.

Not sure this idea has legs... 

What do others think?

**Comment by isidore** [comment]
You probably want 

    var expected = @"
    {
      "tags": [
        {"name": "Serenity"},
        {"name": "Firefly"}
     ]}");
    Approvals. AssertEquals(expected, actual);

**Comment by dalpert-korewireless** [comment]
@isidore should have thought of that. :)

perhaps the benefit would have been using the diff view reporters on a larger sample, but you're right, likely overkill.

**Comment by isidore** [comment]
@dalpert-korewireless 
Approvals.AssertEquals **does** use the reporters on failure. 
On failure, it will create 2 temp files and launch reporter as needed. There are also 2 overrides

    Approvals.AssertEquals(expected,actual, reporter);
    Approvals.AssertEquals<DiffReporter>(expected,actual);
