### ISSUE TITLE
VerifyXml: order of attributes

### ISSUE THREAD

**Issue by halex2005** [approvals/ApprovalTests.Net#191]
I have scenario: 
- apply XSLT-transofrmation to XML1 => got XML2
- apply backward XSLT-transformation to XML2 => got XML3
- verify XML1 is identical to XML3 (elements and attributes are same)

I'd like to use `Approvals.VerifyXml()` like this:

```csharp
void test() {
    Approvals.VerifyXml(XML1);
    // apply transformations here
    Approvals.VerifyXml(XML3);
}
```

The issue is order of attributes.
XML1 has same attributes as XML3 but in different order and my test fails.

Anyone knows workaround for this scenario? I need to compare XMLs structurally.

**Comment by 304NotModified** [comment]
Would be great to add this feature. We have also the same issue, the ordering of the attributes is different in AxoCover vs plain NUnit

**Comment by SimonCropp** [comment]
this should not be fixes as VerifyXml currently sorts attributes. if this is not the case please re-open
