### ISSUE TITLE
PathTooLongException

### ISSUE THREAD

**Issue by RasheR666** [approvals/ApprovalTests.Net#199]
When i'm using UseApprovalSubdirectory attribute and run tests on teamcity we get long path exception for tests.
I can make my path shorten but it don't solve the problem.
Because if root directory of the teamcity will move and get longer path, the problem will return.
Theremore i don't want to change my project structrure and make chaos because i need short paths.

I can offer to use AlphaFS instead System.IO. It's good library for long paths.
If i will have enough time then i do it by myself and make pull request, but if you do it earlier it will be perfect.

**Comment by isidore** [comment]
Never used AlphaFS, but I sure this would be a 20-30 minute session if we
paired. Would you be up for that? What timezone are you in?

Llewellyn Falco
www.approvaltests.com

**Comment by RasheR666** [comment]
My timezone is +5 GMT. But i don't have a lot of free time and it will be hard to synchronize and work in couple in same time.
I offer that i make changes where i start to use AlphaFS and after this you will review this and make some adjustments if need. After this i will review your adjustments and make some adjustments if need.
And so on while we don't make good code for this feature.

**Comment by isidore** [comment]
Seems like that's a lot more than 30 minutes, but go for it.

Llewellyn Falco
www.approvaltests.com

**Comment by RasheR666** [comment]
I'd done all changes. Now i want to push my branch to origin. Need i have any permissions to do this? Because now i can't, maybe i do something wrong. If i do something wrong, can you help me with information what i must do? Because it's my first push to github )

**Comment by RasheR666** [comment]
I've done. You can read comments in pull request and say something to me

**Comment by RasheR666** [comment]
I've done. Can you answer something about my changes?

2017-10-29 10:49 GMT+05:00 Llewellyn Falco <notifications@github.com>:

**Comment by isidore** [comment]
https://www.nuget.org/packages/ApprovalTests/
pushed v3.0.14
