### ISSUE TITLE
Release new version on Nuget

### ISSUE THREAD

**Issue by 304NotModified** [approvals/ApprovalTests.Net#204]
Hi,

It seems that https://github.com/approvals/ApprovalTests.Net/pull/182 still isn't released.

When could we expect a new version? Could we help releasing a new version?

**Comment by 304NotModified** [comment]
Oops duplicate of https://github.com/approvals/ApprovalTests.Net/issues/203

**Comment by 304NotModified** [comment]
I guess this needs to be done:

- update version in CreateNuget.cmd
- run DeployToNuget.cmd

Correct?

**Comment by isidore** [comment]
Done
https://www.nuget.org/packages/ApprovalTests/
