### ISSUE TITLE
Consider marking UnitTestFrameworkNamer.Name as virtual

### ISSUE THREAD

**Issue by GeertvanHorrik** [approvals/ApprovalTests.Net#206]
My suggestion is to make this property virtual. This way it can be overridden.

https://github.com/approvals/ApprovalTests.Net/blob/0c2a590adc317be47fa452a063169f18d18fd08f/ApprovalTests/Namers/UnitTestFrameworkNamer.cs#L29

The reason for this is that I have a shared project with multiple target frameworks (e.g. NET45, NET46, NET47). Then I can postfix this and we can test per-framework as well without having to re-implement the whole base class.

**Comment by isidore** [comment]
We use fody virtualizer so everything should be virtual and public when compiled. Is it not?

**Comment by GeertvanHorrik** [comment]
It broke in the .14 release. Had to revert it. See https://github.com/WildGums/Orc.Squirrel/commit/40b12f3f3ef5401b26c21e27233e31f8bd8216af

**Comment by GeertvanHorrik** [comment]
What could happen is that you updated the fody addins and they used to auto remove / add during an update. However, this is no longer the case (no longer adding). My suggestion is never to commit FodyWeavers changes unless there is a real reason to do so.

**Comment by GeertvanHorrik** [comment]
Just checked, the FodyWeavers.xml looks good.

**Comment by GeertvanHorrik** [comment]
btw here was the original build error:

```
9>C:\CI_WS\Ws\108434\Source\Orc_Squirrel\src\Orc.Squirrel.Tests\Orc.Squirrel.Tests.NET45\App_Packages\ApiApprover.6.0.0\PublicApiApprover.cs(30,36,30,40): error CS0506: 'PublicApiApprover.AssemblyPathNamer.Name': cannot override inherited member 'UnitTestFrameworkNamer.Name' because it is not marked virtual, abstract, or override
```

**Comment by isidore** [comment]
@SimonCropp thoughts?

**Comment by SimonCropp** [comment]
send a pr to fix  :)
