### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by bhushanbapat** [approvals/ApprovalTests.Net#209]
System.NullReferenceException: Object reference not set to an instance of an object. 

Above error thrown on Approvals.VerifyAll[T](Enumerable '1 enumerable, Func`2 formatter.

Not sure why this is happening.

Working fine on another users System. not working on mine.

Attaching Stack Trace.

[Stack Trace.txt](https://github.com/approvals/ApprovalTests.Net/files/1824580/Stack.Trace.txt)

**Comment by SimonCropp** [comment]
can u share some runnable code that reprduces this issue?

**Comment by SimonCropp** [comment]
@bhushanbapat without a way to reproduce this it will not be possible to fix. will close for now. happy to look into it further if u can provide a repro
