### ISSUE TITLE
Approvals with XUnit 2.3.1 on CI (TeamCity)

### ISSUE THREAD

**Issue by stefc** [approvals/ApprovalTests.Net#218]
We've updated xunit 2.3.0 to 2.3.1. On our CI than all our Approvals Test 'll break. 

```
Assert.Equal() Failure
            (pos 0)
Expected: 
Actual:   REP_TESTOBJEKT[0] = {\r\n  "REP_TESTOBJEKT_úúú
            (pos 0)
   at ApprovalTests.Reporters.AssertReporter.AssertEqual(String approvedContent, String receivedContent)
   at ApprovalTests.Reporters.AssertReporter.AssertFileContents(String approved, String received)
   at ApprovalTests.Reporters.AssertReporter.Report(String approved, String received)

```

It seems that the File Load not work's as expected ? On the local developer machines all work's fine. If we switch back to XUnit 2.3.0 also the CI work's fine again. 

Can somebody see this bug also happens ?

**Comment by SimonCropp** [comment]
@stefc cant seem to replicate. can you provide a small solution that reproduces the issue

**Comment by stefc** [comment]
Hi Simon, 
we're recently update our solution to XUnit Version 2.4. and the with that version it work fine. So for us it's ok and the bug-entry can be closed

**Comment by SimonCropp** [comment]
@stefc thanks
