### ISSUE TITLE
GenericDiffReport throws null exception for filetypes if using BeyondCompare 3 and 4

### ISSUE THREAD

**Issue by pmiyasaki** [approvals/ApprovalTests.Net#220]
suggested fix is  "fileTypes = allowedFileTypes ?? GetTextFileTypes;" in ctor of GenericDiffReporter

**Comment by richardsidneyAptus** [comment]
If GenericDiffReporter checked for null and returned correctly instead of throwing an exception. That would support adding new compare tools in the future, if the file types aren't known.

**Comment by SimonCropp** [comment]
this should now be fixed
