### ISSUE TITLE
What to do with alphaFS in netstandard?

### ISSUE THREAD

**Issue by SimonCropp** [approvals/ApprovalTests.Net#223]
So we are gradually moving towards supporting netstandard.

One blocker is the use of AlphaFS. Since it is only designed to extend win32 apis, it is unlikely that it will ever have a netstandard implementation, nor should it. but that leaves approval tests in a weird position. we either need to drop the dependency, or do conditional compilation moving forward.

My preference would be to drop the dependency. 

I know that it was initially brought in to fix a [PathTooLong](https://github.com/approvals/ApprovalTests.Net/issues/199) on a build server ping @RasheR666 . however i think there better solutions/workarounds for that.

 * move the TC checkout directory much higher in the directory structure. eg `c:\code`
 * move to at least net 462 and use the long path support https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/

Dropping AlphaFS also result in one less dependency which makes me happy :)

So @isidore thoughts?

**Comment by RasheR666** [comment]
Hello. Is .netstadard supports long paths?
Can i use .netstandard library at .net 4.5 application?

**Comment by RasheR666** [comment]
It is yours project, that's why you can decide what to do )
I will check after your release long paths supporting on win 10.

**Comment by RasheR666** [comment]
I think if i don't understand how to configure new version for working with long paths then i will use my fork till moment when i not solve this problem.
