### ISSUE TITLE
ScrubPaths unixPathRegex is over matching and removing real data

### ISSUE THREAD

**Issue by williamdenton** [approvals/ApprovalTests.Net#242]
The unix file scrubber matches more than it should

https://github.com/approvals/ApprovalTests.Net/blob/bf133891f4fa768d859336418f9849ef53c134f3/ApprovalTests/Utilities/StackTraceScrubber.cs#L21-L29

the regex `\/[\/\w.\s-]+\/` also matches:

`https://localhost/` which is replaced with `https:.../`
`03/01/2010` which is replace with `03.../2010`

**Comment by SimonCropp** [comment]
@williamdenton perhaps submit a pr with a fix?

**Comment by williamdenton** [comment]
Ok, I'll see if I can. Worried it will be a breaking change. 

I'd also like to be able to fix the file paths so Unix vs windows paths aren't different.  Which probably means changing  `/` to `\` if it's a path

**Comment by SimonCropp** [comment]
@williamdenton we decided that including the stack trace in the verification is rarely useful. As such we have done the following

- obsolete Approvals.Verify(Exception e)
- Add Approvals.VerifyExceptionWithStacktrace(Exception e). replaces Approvals.Verify(Exception e)
- Add Approvals.VerifyException(Exception e) which verifies the exception type and message

**Comment by CarlVerret** [comment]
ExceptionTests.VerifyExceptionWithStacktrace() is language specific.  Won't work on a non english computer....
