### ISSUE TITLE
XUnit2 Reporter not being chosen from FrameworkAssertReporter

### ISSUE THREAD

**Issue by bradtwurst** [approvals/ApprovalTests.Net#246]
In our solution, we have only ApprovalTests developed and have not used xunit Asserts anywhere else within the test projects.

As such, the xunit.assert assembly has not been loaded into the appdomain, which results in the logic to determine is xunit2 is being used to fail.

I have a pull request (provided shortly) with the way that we worked around the issue.

Looking for feedback if this is a correct way to address.

Thanks,
James

**Comment by SimonCropp** [comment]
this should be fixed as part of https://github.com/approvals/ApprovalTests.Net/pull/262
