### ISSUE TITLE
[question] Recommended approach for JSON/object tree testing

### ISSUE THREAD

**Issue by jawn** [approvals/ApprovalTests.Net#248]
Hi,

Glad to see the project and is active again, thanks for that!

Question:
What is a recommended way to create ApprovalTests for
 (Serializable) Object Trees ?

In my old code, I would manually serialize these to a string and compare them:

```
[TestMethod]
[UseReporter(typeof(DiffReporter))]
public void Test()
{
    Response response = SomeCall();

    Approvals.Verify(Serialize(response));
}

public static string Serialize(object data)
{
    if (data == null) throw new ArgumentNullException(nameof(data));
    string xml;
    using (var writer = new StringWriter())
    {
        var namespaces = new XmlSerializerNamespaces();
        namespaces.Add("", "");
        var serializer = new XmlSerializer(data.GetType());
        serializer.Serialize(writer, data, namespaces);
        xml = writer.ToString();
    }

    return xml;
}

```
I want to get rid of this overhead. I guess the StatePrinter is the new direction here. If so (or not), curious to see the recommend approach.

**Comment by SimonCropp** [comment]
it it is raw json i would just use `Approvals.Verify` and pass in the string. if the json string is not nicely formatted, i would pre process it https://stackoverflow.com/questions/4580397/json-formatter-in-c and then verify

for an object i use https://github.com/SimonCropp/ObjectApproval
for your httpresponse case u can use the fact that is support dynamic. eg

```
        var result = httpResponseMessage.Content.ReadAsStringAsync().GetAwaiter().GetResult();

        ObjectApprover.VerifyWithJson(
            new
            {
                result,
                httpResponseMessage.Headers,
                httpResponseMessage.StatusCode
            });
```

```
{
  "result": "the response text",
  "Headers": [
    {
      "Key": "Cache-Control",
      "Value": [
        "max-age=900"
      ]
    }
  ],
  "StatusCode": "OK"
}
```

**Comment by isidore** [comment]
um, you can just use VerifyJson(), it will format for you


    var json = @"{""GivenNames"":""John"",""FamilyName"":""Smith"",""Spouse"":""Jill"",""Address"":{""Street"":""1 Puddle Lane"",""Suburb"":null,""Country"":""USA""},""Childres"":[""Sam"",""Mary""],""Title"":""Mr""}";
     Approvals.VerifyJson(json);

**Comment by SimonCropp** [comment]
seems this is answered :)
