### ISSUE TITLE
package  ApprovalTests.3.0.18-is not compatible with '.NETFramework,Version=v4.6.1'

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [approvals/ApprovalTests.Net#249]
I am trying to install first time ApprovalTests  to project  targeting '.NETFramework,Version=v4.6.1'(VS 2015)
and getting the following
 Install-Package ApprovalTests -Version 3.0.18
Attempting to gather dependency information for package 'ApprovalTests.3.0.18' with respect to project 'Tests\IntegrationTests', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'ApprovalTests.3.0.18' with DependencyBehavior 'Lowest'
Resolving actions to install package 'ApprovalTests.3.0.18'
Resolved actions to install package 'ApprovalTests.3.0.18'
Install failed. Rolling back...
Package 'ApprovalTests.3.0.18' does not exist in project 'IntegrationTests'
Package 'ApprovalTests.3.0.18' does not exist in folder 'C:\GitRepos\ItineraryPublisher\packages'
Install-Package : **Could not install package 'ApprovalTests 3.0.18'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework.** 
For more information, contact the package author.
At line:1 char:1
+ Install-Package ApprovalTests -Version 3.0.18
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
Please suggest, what to do?

Update: I found that I can install package 3.0.15. Does it mean that later versions are only support .Net Core? Also it will be good if NuGet version (or GitHub Releases section) will describe the major changes in each release.

**Comment by SimonCropp** [comment]
you need to either update to VS 2017 or (if u want to continue using 2015) [install tooling for .NET Core tools for Visual Studio 2015](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md)

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

> 1 The versions listed for .NET Framework apply to .NET Core SDK 2.0 and later versions of the tooling. Older versions used a different mapping for .NET Standard 1.5 and higher. You can download tooling for .NET Core tools for Visual Studio 2015 if you cannot upgrade to Visual Studio 2017.
