### ISSUE TITLE
Indicate recent .NET Standard 2.0 requirement

### ISSUE THREAD

**Issue by jawn** [approvals/ApprovalTests.Net#250]
I was surprised when updating a legacy project to a newer ApprovalTests.NET version. 
The cause was the minor version updates require newer .NET Framework versions.

When looking in the nuget versions for ApprovalTests, I see:

* 3.0.15 required .NET Framework v4.5
* 3.0.16 required .NET Framework v4.6.1
* 3.0.17 and higher: .NET Standard 2.0

In understand the decision to support .NET Standard 2.0, however it is surprising these changes show up in a minor version update. Can we clarify the required .NET version in the readme? Also, is the goal to keep supporting .NET Standard 2.0 for a while?

**Comment by mattgwagner** [comment]
Agreed; this was quite confusing, as it definitely is a break from traditional semantic versioning. Patch version bump generally does not completely change the framework requirements.

**Comment by jawn** [comment]
Should I create a PR to add this info to the README?

**Comment by 304NotModified** [comment]
Related #264

**Comment by SimonCropp** [comment]
net461 support has been added back in
