### ISSUE TITLE
UseReporter attribute not working on async xunit tests 

### ISSUE THREAD

**Issue by AlexSugak** [approvals/ApprovalTests.Net#252]
Environment: .NET Core 2.1.403 on a mac, xunit 2.3.1, approvaltests 3.0.18

This works as expected:

```c#
[Fact]
[UseReporter(typeof(DiffReporter))]
public void GET_returns_correct_json()
{
    // ...
    var response = client.GetAsync("/api").Result;
    var body = response.Content.ReadAsStringAsync().Result;
    Approvals.VerifyJson(body);
}
```

This prints "welcome" message from `IntroductionReporter`:

```c#
[Fact]
[UseReporter(typeof(DiffReporter))]
public async Task GET_returns_correct_json()
{
    // ...
    var response = await client.GetAsync("/api");
    var body = await response.Content.ReadAsStringAsync();
    Approvals.VerifyJson(body);
}
```

My guess is that `ApprovalUtilities.CallStack.Caller` fails to find `UseReporter` attribute in case of "async" stack? 
Related to #49 ?

**Comment by flcdrg** [comment]
I think I'm having the same problem with async NUnit tests

**Comment by kenlefeb** [comment]
> Looks like it does work if set at the assembly-level (which probably explains why the ApprovalTests unit tests are not failing)

Thanks for mentioning this!

**Comment by SimonCropp** [comment]
This should be working in the current released version
