### ISSUE TITLE
GetFileNameForStack doesn't work properly for older .NET frameworks version under `DebugType = Portable`

### ISSUE THREAD

**Issue by ForNeVeR** [approvals/ApprovalTests.Net#259]
## The problem

I have this simple `csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp2.1</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="ApprovalTests" Version="3.0.19" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
        <PackageReference Include="xunit" Version="2.4.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    </ItemGroup>
</Project>
```

By default, `<DebugType>` is `Portable`, I believe. That means that [a known issue affecting stack trace availability under older .NET Framework versions](https://github.com/dotnet/sdk/issues/1238) will be in effect.

So, `AttributeStackTraceParser.GetFileNameForStack` won't be able to get any usable file names: https://github.com/approvals/ApprovalTests.Net/blob/8ace2b0e068b5ecfaddee61d64ddb8dabe58589b/ApprovalTests/Namers/StackTraceParsers/AttributeStackTraceParser.cs#L65-L68

That means ApprovalTests.Net won't be able to properly place the text files used for approval.

## The solution

I can't see anything ApprovalTests.Net could do here aside from documenting the issue and maybe trying to detect it at the runtime, and formatting a proper error message in this case.

We could add some small heuristics to try to detect the issue (the main clues are `GetFileName() == null` on the stack trace, SDK-targeting `csproj` and .NET Framework 4.7.1 and lower as the target framework).

**Comment by SimonCropp** [comment]
closing this for now. please provide a repro if it is still an issue

**Comment by ForNeVeR** [comment]
It looks like the issue in question was fixed in a recent .NET SDK: at least, I wasn't able to reproduce the issue with ApprovalTests I was having back then. So, I guess it's okay to stay closed for now, especially having older .NET variants gradually fading away.
