### ISSUE TITLE
Get appveyor CI working

### ISSUE THREAD

**Issue by isidore** [approvals/ApprovalTests.Net#263]

**Comment by jawn** [comment]
If I remember well, @onovotny is eager to help open source projects put CI in place. Is it an idea to ask him for help?

**Comment by 304NotModified** [comment]
Is this still needed? You have Travis running?

**Comment by 304NotModified** [comment]
PS this issue is still pinned ATM

**Comment by SimonCropp** [comment]
Thanks. Unpinned
