### ISSUE TITLE
Approved Text is empty on async Tests in VS-LiveTesting

### ISSUE THREAD

**Issue by mduu** [approvals/ApprovalTests.Net#272]
I ran in to the issue that the tests run successful if triggered manually but fail if they got triggered automatically by VS 2019 Live-Testing. In my tests it only happens for async tests.

It seems the unit-test runs in a temporary directory. Even if I mark the .approved file as "Copy always" it seems not to be copied over to the temporary directory. The strange thing is that it seems works for synchronous tests but not for async.

Tools used:
- .Net Core 2.2
- XUnit
- VS 2019 (latest) Live-Testing
- VS Test-Runner

If have created a GH repo with the code and further instructions on how to reproduce the issue [here...](https://github.com/mduu/approvalTestsWithLiveTesting)

Impact: This issue prevents me from using ApprovalTest .Net in my project as the live-testing has higher prio then the ApprovalTests (but I really miss them) and most of the stuff is async.

**Comment by isidore** [comment]
Would you have some time to pair over skype on this?

**Comment by mduu** [comment]
I don’t have a WindowsVS Box at home so it’s difficult. Can I provide you more information?

**Comment by bbrandt** [comment]
Same issue is occurring with VS 2017 Live Testing with NUnit tests for .NET Core 2.2.  

@isidore I'm ready to pair up and work through it when you are available.  Thanks for all you do!

**Comment by bbrandt** [comment]
We are able to reproduce this in regular tests.  Not only async.

The issue appears to be whether or not you've configured Live Testing with debug symbols.  To solve this:
1. Stop live testing.
2. Turn on debug symbols.  
* Test --> Live Unit Testing --> Options --> Active Solution --> ✅ Enable debug symbol and xml documentation
3. Restart live testing.

**Comment by bbrandt** [comment]
```
using ApprovalTests.Namers.StackTraceParsers;
using ApprovalTests.StackTraceParsers;
using ApprovalUtilities.CallStack;
using System.Linq;

namespace ApprovalTestsWithLiveTesting
{
    internal class MyXUnitParser : XUnitStackTraceParser
    {


        public override string GetFileNameForStack(Caller frame)
        {
            var nonApprovalTests = frame.Parents.Where(c => !c.Class.Namespace.StartsWith("ApprovalTests") && !c.Class.Namespace.StartsWith("ApprovalUtilities")).ToArray();
            
            foreach (var f in nonApprovalTests)
            {
                ApprovalUtilities.SimpleLogger.Logger.Variable("File", f.StackFrame.GetFileName());
                ApprovalUtilities.SimpleLogger.Logger.Variable("Method", f.Method);
                ApprovalUtilities.SimpleLogger.Logger.Variable("Class.Namespace", f.Class.Namespace);
            }

            return nonApprovalTests.Select(c => c.StackFrame.GetFileName()).FirstOrDefault(f => f != null);
        }


    }
}
```

**Comment by isidore** [comment]
:-( this fix breaks all my actual tests for the project....

**Comment by mduu** [comment]
Activating the debug symbols fixes LUT but now Azure DevOps CI-Build has the same issue where the expectation file is empty / non-existent even if I marked it as "Allways copy to local".

**Comment by mduu** [comment]
> Activating the debug symbols fixes LUT but now Azure DevOps CI-Build has the same issue where the expectation file is empty / non-existent even if I marked it as "Allways copy to local".

The problem seems that ApprovalTest .Net does look on the wrong root directory for the .approved.* files. Instead `D:\a\1\s\....` I see a `CMD move` command that copies the .received.json file to `c:\s\....` instead of `d:\a\1\s\...`.

I added the statement `Approvals.UseAssemblyLocationForApprovedFiles();` which breaks my local tests too but does **not** fix the CI build.

How does ApprovalTests .Net handle the root directory (using XUnit with the MSTest Runner Adapter)?

**Comment by mduu** [comment]
Again hit this issue. Any ideas?

**Comment by isidore** [comment]
@mduu @bbrandt Would you have some time to pair over skype on this? Very hard to diagnose on my mach

**Comment by SimonCropp** [comment]
several async bugs have been fixed since this issue. i assume it has been. if not can u provide a stand alone repro
