### ISSUE TITLE
FindAbandonedFiles doesn't work for nested classes

### ISSUE THREAD

**Issue by jamesfoster** [approvals/ApprovalTests.Net#273]
`ApprovalMaintenance.FindAbandonedFiles` splits the file name by dot (.) and treats the first part as the class name and the second part as the test name.

However, when you have nested test classes the file is named as `"Parent.TestClass.TestMethod.approved.txt"`

Perhaps, something a little more recursive is needed?

```
            IEnumerable<MethodInfo> FindApprovalMethods(
                IEnumerable<string> names,
                IList<Type> types
            )
            {
                var nested = types
                   .SelectMany(t => t.GetNestedTypes())
                   .Where(t => t.Name == names.First())
                   .ToList();

                var methods = types
                   .SelectMany(t => t.GetMethods())
                   .Where(t => t.Name == names.First());

                if (!nested.Any())
                    return methods;

                return methods
                   .Concat(FindApprovalMethods(names.Skip(1), nested));
            }
```

**Comment by jamesfoster** [comment]
Should it also not find received files as well as approved files?

**Comment by SimonCropp** [comment]
@jamesfoster this will be fixed on the next release

> Should it also not find received files as well as approved files?

No. you should add an exclude pattern to your source control so they are never commited
