### ISSUE TITLE
V4 has assemblyversion 3.0.0.0

### ISSUE THREAD

**Issue by 304NotModified** [approvals/ApprovalTests.Net#283]
Hi, 

I see version 4 has assemblyversion 3.0.0.0. 

Is  V4 (binary) backswardscompabilbe with V3?

**Comment by SimonCropp** [comment]
@304NotModified v4 is mainly backwards compatible with v3. 

We locked the assemblyversion in the v3 timeframe, and it will continue to remain a v3 forever to avoid any binding redirect issues. 

The reasoning for this is to ensuring that downstream nugets continue to work (without biding redirects) when a new major of approvaltests is released.

So sorry for the confusion.

moving forward you should rely on the nuget version, which will use semantic versioing
