### ISSUE TITLE
CombinationApprovals.VerifyAllCombinations failing for .NET framework 4.6 in build pipleline

### ISSUE THREAD

**Issue by JulianJJ** [approvals/ApprovalTests.Net#285]
we faced one issue with CombinationApprovals.VerifyAllCombinations where in build pipeline the build was failing. It was fixed in .NET Core version update.
However the same issue is there in .NET framework 4.6 which we are also using.
The latest release of ApprovalsTests 4.0.0 only supports  .NETStandard 2.0.
We are using .Net Framework 4.6 can’t upgrade as of now.
Also we are using ApprovalTest Nuget package 3.0.15 and can’t update to higher version as the higher version doesn’t supports .Net Framework 4.6

**Comment by SimonCropp** [comment]
You dont have to change the version of your production code, but you should still be able to move your test target framework to 4.6.1? Or even better move your tests to 472?
