### ISSUE TITLE
Problem with source path

### ISSUE THREAD

**Issue by richarth** [approvals/ApprovalTests.Net#288]
Hi,

I have some approval tests that I'm running on our CI server (Gitlab using a Mono Docker image).  When the tests run we get the following error:

ApprovalTests is not detecting the proper source path

I've edited my tests project file and ensured that debug type is full for all of the build configurations but that hasn't helped.

I'm sure there is something about the environment that is causing this but I'm not sure what path it's referring too.

Thanks for your help.

**Comment by SimonCropp** [comment]
@richarth what version are you running? and does the same problem occur on 4.0.0?

**Comment by richarth** [comment]
Hi,

Thanks for getting back to me.  I'm using 4.2.0.

**Comment by SimonCropp** [comment]
And does the same problem occur in v4.0?

**Comment by richarth** [comment]
Yes, I get the same problem with 4.0.

**Comment by BlythMeister** [comment]
out of interest, are you using R# to run the tests?

**Comment by BlythMeister** [comment]
At a guess...this commit looks suspicious...https://github.com/approvals/ApprovalTests.Net/commit/d2968ec861fdbfa1295f85d2f5dcdc74fdc2e6ab
Since the error is mentioning this debug type :)

**Comment by SimonCropp** [comment]
What version of .net r u running on the ci server?

**Comment by BlythMeister** [comment]
.net core 2.2

**Comment by richarth** [comment]
We're using the latest Mono Docker image and our solution is targeting 4.7.2 of the .Net Framework.

**Comment by SimonCropp** [comment]
can u try version 4.2.1-beta.1

**Comment by richarth** [comment]
Hi,

I've tried with 4.2.1-beta.1 and 4.2.2 but I'm still getting the same error unfortunately.

```
ApprovalTests is not detecting the proper source path
  
  This is probably because you're missing the following
  line in your .csproj file:
  	  <DebugType>full</DebugType>
  in the
  <Project>
    <PropertyGroup>
  element.
  
  Solution:
  a) Add <DebugType>full</DebugType> to your .csproj file.
  b) OR Build->Advanced->DebugInfo to Full
  Type: System.Exception
  Source: ApprovalTests
  StackTrace:
    ApprovalTests.Namers.StackTraceParsers.StackTraceParser.get_SourcePath () [0x00033]
      <e5eb23474ea84065b2d59eb768ba7ae5>:0
    ApprovalTests.Namers.UnitTestFrameworkNamer.get_SourcePath () [0x00000]
      <e5eb23474ea84065b2d59eb768ba7ae5>:0
    ApprovalTests.Approvers.FileApprover.Approve () [0x00001]
      <e5eb23474ea84065b2d59eb768ba7ae5>:0
    ApprovalTests.Core.Approver.Verify (ApprovalTests.Core.IApprovalApprover approver, ApprovalTests.Core.IApprovalFailureReporter reporter) [0x00001]
      <e5eb23474ea84065b2d59eb768ba7ae5>:0
    ApprovalTests.Approvals.Verify (ApprovalTests.Core.IApprovalApprover approver, ApprovalTests.Core.IApprovalFailureReporter reporter) [0x00001]
      <e5eb23474ea84065b2d59eb768ba7ae5>:0
    ApprovalTests.Approvals.Verify (ApprovalTests.Core.IApprovalWriter writer, ApprovalTests.Core.IApprovalNamer namer, ApprovalTests.Core.IApprovalFailureReporter reporter) [0x00044]
      <e5eb23474ea84065b2d59eb768ba7ae5>:0
    ApprovalTests.Approvals.Verify (ApprovalTests.Core.IApprovalWriter writer) [0x0000f]
      <e5eb23474ea84065b2d59eb768ba7ae5>:0
    ApprovalTests.Xml.XmlApprovals.VerifyText (System.String text, System.String fileExtensionWithoutDot, System.Boolean safely, System.Func`2[T,TResult] scrubber) [0x00047]
      <e5eb23474ea84065b2d59eb768ba7ae5>:0
    ApprovalTests.Html.HtmlApprovals.VerifyHtml (System.String html, System.Func`2[T,TResult] scrubber) [0x00001]
      <e5eb23474ea84065b2d59eb768ba7ae5>:0
    ApprovalTests.Approvals.VerifyHtml (System.String html) [0x00001]
      <e5eb23474ea84065b2d59eb768ba7ae5>:0
```

**Comment by SimonCropp** [comment]
FYI i have given up looking at this and created a bridging nuget that maps approval tests to xunit https://github.com/SimonCropp/XunitLogger#xunitapprovaltests

**Comment by richarth** [comment]
Hi,

Thanks for the update.  I'm currently using MS Test, could I just check please before I do so, that I would need to convert the tests to XUnit for the bridging to work?

Thanks
Richard

**Comment by SimonCropp** [comment]
@richarth yep, unfortunately my extension only works for xunit. u would either need to move to xunit or write a similar bridging library for mstest

**Comment by richarth** [comment]
I can confirm that switching to xUnit and using your bridging library has gotten the tests running successfully on CI.  Thanks a lot for the help.

**Comment by jawn** [comment]
> FYI i have given up looking at this and created a bridging nuget that maps approval tests to xunit > https://github.com/SimonCropp/XunitLogger#xunitapprovaltests

Should this be added to the README of https://github.com/approvals/ApprovalTests.Net ?
