### ISSUE TITLE
Support .NET Core 3 Wpf / WinForms

### ISSUE THREAD

**Issue by jakub-klima** [approvals/ApprovalTests.Net#289]
It would be helpful for ApprovalTests.Wpf and ApprovalTests.WinForms to work also for .NET Core 3.

**Comment by SimonCropp** [comment]
WPF done: https://github.com/approvals/ApprovalTests.Net.Wpf/milestone/2?closed=1

**Comment by SimonCropp** [comment]
This project is not being actively maintained. Instead consider using [Verify](https://github.com/VerifyTests/Verify/). See [Migrating from ApprovalTests](https://github.com/VerifyTests/Verify/blob/main/docs/compared-to-approvaltests.md#migrating-from-approvaltests) for more information.
