### ISSUE TITLE
[question] verify generic list of data classes does not include property values

### ISSUE THREAD

**Issue by jawn** [approvals/ApprovalTests.Net#320]
Given this code
```
public class Customer
{
  public string Name { get; set; }
}

[Test]
public void Repro()
{
    var customers = new List<Customer>();
    customers.Add(new Customer { Name = "John"});
    customers.Add(new Customer { Name = "Alice"});

    Approvals.VerifyAll(customers, "customers");
}
```

Expected result:
* Approval file contains customer names

Actual result:
* Approval file does not contain customer names

```
customers[0] = Itineris.UMAX.PZEM.Services.Tests.Aif.Customer
customers[1] = Itineris.UMAX.PZEM.Services.Tests.Aif.Customer

```

Is this by design?

**Comment by SimonCropp** [comment]
> Is this by design?

No. but it is a constraint of the implementation. try https://github.com/approvals/ApprovalTests.Net.StatePrinter or https://github.com/SimonCropp/ObjectApproval

**Comment by jawn** [comment]
I see ObjectApproval is archived and StatePrinter is active but doesn't support .NET Core or standard yet. Any plans for that?

**Comment by SimonCropp** [comment]
@jawn i have forked approval test https://github.com/SimonCropp/Verify. that project contains both the functionality of ObjectApproval  and ApprovalTest. still beta but will be moved to stable in the next few days.

**Comment by SimonCropp** [comment]
@isidore what do u want to do with ObjectApproval ? happy to see it die or would u like to transfer it to the approvals org?

**Comment by jawn** [comment]
I am not attached to ObjectApproval, I am creating new tests in a .NET Core 3.x environment.

I'll give Verify a go and if it works well, either suits me. I prefer one maintained library over multiple half-maintained ones.

**Comment by jawn** [comment]
Bummer, it seems Verify isn't test framework agnostic and assumes xUnit.

While xUnit is great it doesn't support parallel data driven testing, which is why I tend to start with NUnit on new projects.

Is there a way to call the Verify stuff directly?

**Comment by SimonCropp** [comment]
yep. i decided to start with xunit support first and add nunit alter

what do u mean by “parallel data driven testing”?

**Comment by jawn** [comment]
> what do u mean by “parallel data driven testing”?

The combination of this sample with a custom attribute that gets its data from a test dat a file (CSV, Excel, JSON...)
https://github.com/jawn/dotnet-parallel-parameterized-tests/blob/master/netfx-nunit/Tests/Tests.cs

**Comment by jawn** [comment]
I'll keep an eye on the Verify library and for now, the following does the trick for me without any additional libraries.

```
        private void VerifyResponse<T>(IEnumerable<T> enumerable)
        {
            string serializedResponse = System.Text.JsonSerializer.Serialize(enumerable);

            Approvals.VerifyJson(serializedResponse);
        }

```
