### ISSUE TITLE
EmptyFiles 0.7. reference - ASP.net core 3.1 The type initializer for 'EmptyFiles' threw an exception.

### ISSUE THREAD

**Issue by CarlVerret** [approvals/ApprovalTests.Net#329]
Hi,
Just to let you know a little problem ; using approvals 4.5.1, there's a little problem with the EmptyFiles reference.  It doesn't find the assembly and fails when the DiffReporter is trying to write files.
`public static void EnsureFileExists(string approved)`

After manually adding the reference to EmptyFiles in my unit test project, the probem is gone.

**Comment by CarlVerret** [comment]
Hi,
Just to let you know a little problem ; using approvals 4.5.1, theres a problem with the EmptyFiles reference.  It doesn't find the assembly and fails when the DiffReporter is trying to write files.
`public static void EnsureFileExists(string approved)`

After manually adding the reference to EmptyFiles in my unit test project, the probem is gone.

**Comment by jawn** [comment]
Same issue here

**Comment by CarlVerret** [comment]
did my workaround worked for you ?

**Comment by jawn** [comment]
Yes, thanks, I confirm the workaround helps!

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
