### ISSUE TITLE
Tests failing on build server, approved file empty?

### ISSUE THREAD

**Issue by RussKie** [approvals/ApprovalTests.Net#331]
I'm having a drama with test failing in a build server (AzDO), and I'm not sure what I'm doing wrong.
I don't have an access to build agents, only to the [logs](https://dev.azure.com/dnceng/public/_build/results?buildId=555301&view=results). 

The logs contain the following:
```
xUnit.net Console Runner v2.4.1 (64-bit .NET Core 5.0.0-alpha1.19514.1)
  Discovering: System.Windows.Forms.Design.Tests
  Discovered:  System.Windows.Forms.Design.Tests
  Starting:    System.Windows.Forms.Design.Tests

cmd /c move /Y "D:\_\src\System.Windows.Forms.Design\tests\UnitTests\TypeMembersAttributeDecorationTests.VerifyAttributes.received.txt" "D:\_\src\System.Windows.Forms.Design\tests\UnitTests\TypeMembersAttributeDecorationTests.VerifyAttributes.approved.txt"

    System.Windows.Forms.Design.Tests.TypeMembersAttributeDecorationTests.VerifyAttributes [FAIL]
      Assert.Equal() Failure
      Assert.Equal() Failure
                 (pos 0)
      Expected: 
      Actual:   System.ComponentModel.Design.BinaryEditor���
                 (pos 0)
      Stack Trace:

... (snip) ...
```

It looks to me as though before the tests the approved file is written over with a blank file, causing the assertion to fail.

Looks like that command is coming from
https://github.com/approvals/ApprovalTests.Net/blob/9e4dfbc60658136410738f502da3064f5d22f8fa/src/ApprovalTests/Reporters/QuietReporter.cs#L23-L26

Any ideas as to why is getting invoked?

I have no failures running tests locally (where I have P4Mege installed) and a blank VM (Where I have no diff tools installed).
Source: https://github.com/dotnet/winforms/commit/d10d2b17dc1d8d708dac56e6607ff33b7d4ed6ff

**Comment by RussKie** [comment]
I did further tests on a VM (where I have no difftools installed), adding a space to the approved file and re-running tests. The tests failed as expected, and the same command appeared as well.

```
xUnit.net Console Runner v2.4.1 (64-bit .NET Core 5.0.0-alpha1.19514.1)
  Discovering: System.Windows.Forms.Primitives.Tests
  Discovered:  System.Windows.Forms.Primitives.Tests
  Starting:    System.Windows.Forms.Primitives.Tests
cmd /c move /Y "C:\Dev\winforms\src\System.Windows.Forms.Primitives\tests\TypeMembersAttributeDecorationTests.VerifyAttributes.received.txt" "C:\Dev\winforms\src\System.Windows.Forms.Primitives\tests\TypeMembersAttributeDecorationTests.VerifyAttributes.approved.txt"
    System.Windows.Forms.Primitives.Tests.TypeMembersAttributeDecorationTests.VerifyAttributes [FAIL]
      Assert.Equal() Failure
                 (pos 0)
      Expected:  BooleanExtensions => System.Runtime.Compúúú
      Actual:   BooleanExtensions => System.Runtime.Compiúúú
                 (pos 0)
      Stack Trace:
... (snip) ...
```

So looks like the approval file on a build server is somehow blank... Any clues?

**Comment by SimonCropp** [comment]
This project is not being actively maintained. Instead consider using [Verify](https://github.com/VerifyTests/Verify/). See [Migrating from ApprovalTests](https://github.com/VerifyTests/Verify/blob/main/docs/compared-to-approvaltests.md#migrating-from-approvaltests) for more information.
