### ISSUE TITLE
Fail with Deterministic builds

### ISSUE THREAD

**Issue by clairernovotny** [approvals/ApprovalTests.Net#335]
When `ContinuousIntegrationBuild` and `Deterministic` properties are set to true, as is recommended for CI builds, tests fail:

Looking at the log, I see this:
```
cmd /c move /Y "d:\_\Rx.NET\Source\tests\Tests.System.Reactive.ApiApprovals\Api\ApiApprovalTests.Core.received.cs" "d:\_\Rx.NET\Source\tests\Tests.System.Reactive.ApiApprovals\Api\ApiApprovalTests.Core.approved.cs"
[xUnit.net 00:00:05.25]     ReactiveTests.Tests.Api.ApiApprovalTests.Core [FAIL]
cmd /c move /Y "d:\_\Rx.NET\Source\tests\Tests.System.Reactive.ApiApprovals\Api\ApiApprovalTests.Testing.received.cs" "d:\_\Rx.NET\Source\tests\Tests.System.Reactive.ApiApprovals\Api\ApiApprovalTests.Testing.approved.cs"
  X ReactiveTests.Tests.Api.ApiApprovalTests.Core [3s 393ms]
```

What's interesting is that it's using `_` in the path when the source directory is `d:\a\1\s`. 

That `_` comes from the `DeterministicSourcePaths` flag which gets sent to the compiler. It should not be relied upon for determining where on the file system the file is in these scenarios.

**Comment by SimonCropp** [comment]
@isidore i dont think there is a workaround for this. if the pdb doesnt have the true code location we r stuck?

**Comment by clairernovotny** [comment]
As more projects move towards supporting deterministic builds, they'll all get these virtual paths. Why do you need to know the source path to move a file around? Can't you write to a temp directory and compare from there?

**Comment by clairernovotny** [comment]
As this scenario is only intended for CI environments, one workaround could be to require that an env variable be set (or auto detected) as to where the source code base path is. Then you could substitute the `/_/` with that.

**Comment by RussKie** [comment]
Looks like the same issue as i have reported in #331.

**Comment by SimonCropp** [comment]
so i think the workaround for this is to add the following to you test projects

```
    <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>
    <Deterministic>false</Deterministic>
```

thinking of making the above added by default to anyone using approval tests or verify. thoughts?

**Comment by RussKie** [comment]
I tried that, it didn't seem to work, the build is still failing.

Commit: https://github.com/dotnet/winforms/commit/8f0a3db2a5021544f90cc5253cb2c4642a1be895
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=578916&view=results

Source project: `D:\a\1\s\src\System.Windows.Forms\src\System.Windows.Forms.csproj`
Test assembly: `D:\a\1\s\artifacts\bin\System.Windows.Forms.Tests\Release\netcoreapp5.0\System.Windows.Forms.Tests.dll`
![image](https://user-images.githubusercontent.com/4403806/77866919-aeaa5400-7280-11ea-913e-99b082844e36.png)

Logs show:
```
cmd /c move /Y "D:\_\src\System.Windows.Forms\tests\UnitTests\TypeMembersAttributeDecorationTests.VerifyAttributes.received.txt" "D:\_\src\System.Windows.Forms\tests\UnitTests\TypeMembersAttributeDecorationTests.VerifyAttributes.approved.txt"
    System.Windows.Forms.Tests.Serialization.TypeMembersAttributeDecorationTests.VerifyAttributes [FAIL]
      Assert.Equal() Failure
                 (pos 0)
      Expected: 
      Actual:   Microsoft.CodeAnalysis.EmbeddedAttribute ���
                 (pos 0)
```

**Comment by SimonCropp** [comment]
@RussKie sorry. i only verified the workaround with Verify. looks like i incorrectly assumed it would also  work for approvaltests

**Comment by RussKie** [comment]
If you have any more ideas you want me to try, just holler

**Comment by SimonCropp** [comment]
@RussKie i need a stand alone repro with a script that reproduces it.

**Comment by SimonCropp** [comment]
@RussKie sigh. scratch that. 30 seconds later i got a repro working

**Comment by LittleLittleCloud** [comment]
Hitting the same issue here

**Comment by LittleLittleCloud** [comment]
My workaround solution is to implement a customer namer, target `SourcePath` to the directory that saves approve.txt maunally, then register it using `RegisterDefaultNamerCreation`. Hope this can help

**Comment by SimonCropp** [comment]
@LittleLittleCloud @RussKie does it happen for Verify?

**Comment by RussKie** [comment]
We don't use Verify, so can't comment on this, sorry

**Comment by NikiforovAll** [comment]
Same issue. This happened with me for `Approvals.Verify(...);`

Ref: https://github.com/dotnet/command-line-api/pull/898

**Comment by SimonCropp** [comment]
@NikiforovAll @RussKie  can u try adding the following to your test csproj?

```
<Deterministic>false</Deterministic>
<DeterministicSourcePaths>false</DeterministicSourcePaths>
```

**Comment by NikiforovAll** [comment]
@SimonCropp fixes the issue. Do you think we could add something environment-aware to deal with deterministic builds?

**Comment by SimonCropp** [comment]
i will put that fix into approval tests

**Comment by NikiforovAll** [comment]
I think deterministic build behavior properties are defined outside of ApprovalTests. So I'm not sure about fix based on overriding `DeterministicSourcePaths` property.

**Comment by SimonCropp** [comment]
can u please try version 5.2.2

**Comment by NikiforovAll** [comment]
That does the trick. Thank you @SimonCropp 🙂

**Comment by SimonCropp** [comment]
sorry for the delay peoples
