### ISSUE TITLE
Diff tool is different since v.5

### ISSUE THREAD

**Issue by CarlVerret** [approvals/ApprovalTests.Net#346]
Hi,

While TurtoiseMerge is the tool have been using since a long time as DiffReporter, now it's VSCode that launches since I've upgraded to V.5.0.0.  Is there somewhere we can configure to specify Turtoise instead of VSCode ?

thanks.

**Comment by SimonCropp** [comment]
@CarlVerret what is the full path to your TurtoiseMerge  exe?

**Comment by CarlVerret** [comment]
"C:\Program Files\TortoiseSVN\bin\TortoiseMerge.exe"

**Comment by SimonCropp** [comment]
can u try 5.0.2

**Comment by CarlVerret** [comment]
Made the update.  Something kinda strange..... In a whole new project (xUnitTest project template .net core 3.1) it does launch tortoise!  In my old solution, it keeps launching Visual Studio (no more vs code!) as the diff tool.

**Comment by CarlVerret** [comment]
my "System.TypeLoadException : Could not load type" problem was probably related to referencing both 5.0 and 4.x version of Approvals.net in my whole solution (as I have more than 1 test project in my solution)

**Comment by CarlVerret** [comment]
If this could be useful, when I integrate my xUnitTest project inside my solution initial solution, it does launch vstudio diff instead of tortoise.  Feels like there's something in the solution's configuration that have something to do with the diff tool that is launched.  I've added it by the "add existing project" in my solution without even changing or refering something else.

**Comment by SimonCropp** [comment]
the tool order is configurable, both in code and by an environment variable https://github.com/SimonCropp/DiffEngine/blob/master/docs/diff-tool.order.md

note that page also has the default order listed. i you have a solution that is not behaving as expected, can u upload that solution to a GH repo and give me the url

**Comment by CarlVerret** [comment]
hi,  looks like there was something in my .vs folder that was making some trouble.... Just flushed it and now TortoiseMerge is launched as before.
There is still something, when it tries to compare the received file with an approved one, it says ; The text is identical but the files do not match ! Encoding (UTF8 BOM, ASCII) ...

**Comment by CarlVerret** [comment]
after some research .... in both cases a simple test without any approved or received file 

Going back to approval 4.53, the empty files (both received and approved) have UTF8-BOM encoding.

After updating to 5.04, left file (received) encoding is UTF8-BOM but right file (empty approved) encoding is ASCII !

**Comment by SimonCropp** [comment]
can u please share a failing unit test as a pull request

**Comment by CarlVerret** [comment]
can't figure how I can pull request something.  looks like I don,t have the rights.... here's a zip file of my test and both received and approved with diff encodings.
[failing.zip](https://github.com/approvals/ApprovalTests.Net/files/4493637/failing.zip)

**Comment by CarlVerret** [comment]
DiffRunne => Launch => AllFiles.TryCreateFile(targetFile, true) 
Looks like Emptyfiles.TryCreateFile is creating an ASCII file instead of a UTF8-BOM file.

**Comment by CarlVerret** [comment]
I just pushed some modification that solve the problem.  Could you please accept my pull request ?

Thanks
