### ISSUE TITLE
Not able to edit approved file in VisualStudio 2019

### ISSUE THREAD

**Issue by softwarebandit** [approvals/ApprovalTests.Net#388]
Using DiffReporter.
When the Diff window opens up. The approved file shows up on the left (read-only) and the received file shows up on the right side (read-write mode). 
It should be the opposite. I should be able to update the approved file. There's not need to edit the received file since that's generated automatically.

**Comment by softwarebandit** [comment]
My current workaround is to create a custom reporter and switch around the Report() method parameters:
```
    public class MyDiffReporter : DiffReporter
    {
        public override void Report(string approved, string received)
        {
            base.Report(received, approved);
        }
    }
```

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
