### ISSUE TITLE
Join to .NET Foundation

### ISSUE THREAD

**Issue by danielmeza** [approvals/ApprovalTests.Net#395]
This issue is for tracking the join to .NET Foundation

**Comment by SimonCropp** [comment]
@danielmeza what is the value of ApprovalTests joining the DNF?

**Comment by danielmeza** [comment]
@SimonCropp https://dotnetfoundation.org/projects/why-join

**Comment by SimonCropp** [comment]
@danielmeza can you point to a few projects that have successfully received such assistance, so i can see what it looks like in practice?

**Comment by danielmeza** [comment]
@SimonCropp let me search some one.

**Comment by danielmeza** [comment]
Here is one https://github.com/App-vNext/Polly/ https://dotnetfoundation.org/projects/polly 
the complete list here https://dotnetfoundation.org/projects

**Comment by SimonCropp** [comment]
yep Polly is in the dnf. but i dont really think giving the polly description and a link back is enough to justify the value of its membership.

**Comment by SimonCropp** [comment]
@danielmeza on a another note, why do you want ApprovalTests to join the DNF?

**Comment by danielmeza** [comment]
Well the only reason I have is to make this project more visible and to feel safe while I use it, not because is not save but because it will be here for a long time no maters wat happen with the maintainers. The last one is a personal and humble desire.

**Comment by isidore** [comment]
Looking into this. Thanks for the suggest.
