### ISSUE TITLE
The tutorials section on Docs are empty. 

### ISSUE THREAD

**Issue by danielmeza** [approvals/ApprovalTests.Net#396]
The tutorials section on Docs are empty. 
Noting more to say.

**Comment by SimonCropp** [comment]
This project is not being actively maintained. Instead consider using [Verify](https://github.com/VerifyTests/Verify/). See [Migrating from ApprovalTests](https://github.com/VerifyTests/Verify/blob/main/docs/compared-to-approvaltests.md#migrating-from-approvaltests) for more information.
