### ISSUE TITLE
xUnit test framework not found when calling Approvals.Verify from an async extension

### ISSUE THREAD

**Issue by edgarssults** [approvals/ApprovalTests.Net#405]
I've forked the repository and added a failing test example here: https://github.com/edgarssults/ApprovalTests.Net/tree/async-extension-failure

I was attempting to add a fluent extension for verifying async results like HTTP calls and encountered this problem. The test fails with the `Could Not Detect Test Framework` error. I saw that there's been some work done to fix async usage, but my use case doesn't work yet. As I understand getting a usable stack trace from an async method is difficult.

The solution that I used in my project involved a custom namer and using `CallerFilePath` and `CallerMemberName` attributes in the extension. This lets me get the necessary information, but might not be a generic enough solution. I've included some passing tests with this solution in the branch.

Anyway, maybe you can use this to fix this use case?

**Comment by SimonCropp** [comment]
i recommend moving to https://github.com/VerifyTests/Verify since it does not rely on stack trace parsing
