### ISSUE TITLE
Add possibility to ignore font subsets during pdf comparison

### ISSUE THREAD

**Issue by NikiforovAll** [approvals/ApprovalTests.Net#409]
Since the subset names for embedded fonts are generated in an indeterministic way. It is not possible to use approval tests in this case. My suggestion is to extend _PdfScrubber_, so 6 digit prefix is not involved in the comparison.

Ref: https://tex.stackexchange.com/questions/156429/what-is-the-scheme-of-fonts-naming-in-pdfs-generated-by-latex-and-other-software

E.g. `FAUUBT` is a randomly generated subset name.
`<</Type/FontDescriptor/Ascent 765/CapHeight 713/Descent -240/FontBBox[-549 -270 1204 1047]/FontName/` + **FAUUBT** + `+OpenSans/ItalicAngle 0/StemV 80/FontFile2 23 0 R/Flags 32>>`

If you think it is a valid addition to this library, I will be glad to implement it.

**Comment by isidore** [comment]
I'd be up for this, can we setup a time to pair next week?

**Comment by NikiforovAll** [comment]
@isidore sound fun, let's do that. How are we going to do that?

**Comment by SimonCropp** [comment]
This project is not being actively maintained. Instead consider using [Verify](https://github.com/VerifyTests/Verify/). See [Migrating from ApprovalTests](https://github.com/VerifyTests/Verify/blob/main/docs/compared-to-approvaltests.md#migrating-from-approvaltests) for more information.
