### ISSUE TITLE
PdfScrubber doesn't scrub modified date

### ISSUE THREAD

**Issue by togakangaroo** [approvals/ApprovalTests.Net#47]
I am using `VerifyPdfFile` but the verification is always failing due to 

```
/ModDate (D:20131119191132-06'00')
```

PdfScrubber scrubs out the created date but not the `ModDate`

**Comment by ValdisThomann** [comment]
Have created #281 to resolve this issue

**Comment by michaelhuang1168** [comment]
The latest version of approval test takes care of the date stamp but not the id at the bottom, any workarounds?

coming from this link
https://stackoverflow.com/questions/20085899/what-is-the-id-field-in-a-pdf-file

**Comment by jawn** [comment]
> The latest version of approval test takes care of the date stamp but not the id at the bottom, any workarounds?
> 
> coming from this link
> https://stackoverflow.com/questions/20085899/what-is-the-id-field-in-a-pdf-file

This issue is closed, maybe log a new issue?
