### ISSUE TITLE
Feature Reqest: dotnet approve all

### ISSUE THREAD

**Issue by marhoily** [approvals/ApprovalTests.Net#503]
Is there may be a [.net CLI tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) for batch approve?

**Comment by SimonCropp** [comment]
there isnt at the moment. the closest things are 

 * AllFailingTestsClipboardReporter : https://github.com/approvals/ApprovalTests.Net/blob/master/docs/ApprovalTests/mdsource/Reporters.source.md#auto-approving-reporters
 * DiffEngineTray: https://github.com/VerifyTests/DiffEngine/blob/master/docs/tray.md
