### ISSUE TITLE
Commands generated by AllFailingTestsClipboardReporter only works on Windows

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.Net#510]
Steps to reproduce:

On Mac or Linux...

1. Add this to your ApprovalTests.Config.cs:   
    `[assembly: UseReporter(typeof(AllFailingTestsClipboardReporter))]`
1. Make some approval tests fail
1. Paste the clipboard on to a console window...

**Expected behaviour:**
`*.approved.*` are updated, for the failing tests

**Actual behaviour**:
a bunch of errors `command not found: cmd` 

This looks to be the cause:

https://github.com/approvals/ApprovalTests.Net/blob/d3d4a978aa297444f284eb1a7d5b58f442e0869a/src/ApprovalTests/Reporters/QuietReporter.cs#L25

**Comment by claremacrae** [comment]
I see this was already logged in #437 - this ticket answers the question there about what the problem was, I think.

**Comment by claremacrae** [comment]
The simplest fix would be to change `cmd /c move /Y` to `cp` if not on Windows...

There are complications if the user has aliased `cp` to `cp -i` - to force a prompt, but I'd prefer to start with a solution that works for many users, than wait for a perfect one!

Or - having read the following - use `\cp` instead, which will bypass any alias (and has been in my muscle memory for `\rm` for many years, so I know it works well...

https://unix.stackexchange.com/a/146442/186988

**Comment by SimonCropp** [comment]
@claremacrae can u try 5.4.6

**Comment by claremacrae** [comment]
> @claremacrae can u try 5.4.6

Perfect - thanks @SimonCropp !

**Comment by claremacrae** [comment]
@SimonCropp the only weird thing is that this doesn't show up in the [releases page](https://github.com/approvals/ApprovalTests.Net/releases) which thinks that 5.4.4 was the last release....
