### ISSUE TITLE
These files have different encodings. Left file: Unicode (UTF-8) with signature. Right file: Central European (Windows). You can resolve the difference by saving the right file with the encoding Unicode (UTF-8) with signature.

### ISSUE THREAD

**Issue by dariusz-wozniak** [approvals/ApprovalTests.Net#524]
When using VisualStudioReporter and when copying .received to .approved, I'm receiving the following error:

> These files have different encodings. Left file: Unicode (UTF-8) with signature. Right file: Central European (Windows). You can resolve the difference by saving the right file with the encoding Unicode (UTF-8) with signature.  Click to learn more 

![image](https://user-images.githubusercontent.com/5969160/113708839-0a07f100-96e2-11eb-8b4f-2146f402361f.png)

Using:
- ApprovalTests 5.4.7
- Visual Studio 16.9.3

Is it possible to skip encoding check? Or, is it possible to fix the above scenario?

**Comment by SimonCropp** [comment]
* so when you clone your repository. what encoding are you `.approved` files?
 * does this happen if you use diffenginetray? https://github.com/VerifyTests/DiffEngine/blob/master/docs/tray.md

**Comment by SimonCropp** [comment]
will close this wince there i no response. happy to reopen if it is still an issue.

Also can you provide a downloadable minimal repro.

**Comment by SimonCropp** [comment]
if Empty file is UTF-8 with BOM and then is a different encoding after you do a copy paste in VS, then doesnt that imply it is a problem with VS?
