### ISSUE TITLE
Set project to not conflict with NCrunch

### ISSUE THREAD

**Issue by RefactoringPipelinesTeam** [approvals/ApprovalTests.Net#534]
This should automatically be added to your project file when you nuget install ApprovalTests.

```
	<DefaultItemExcludes>*.received.*</DefaultItemExcludes>
```

This should fix NCrunch looping.

**Comment by claremacrae** [comment]
Source of the text above:
https://forum.ncrunch.net/yaf_postst3104_ApprovalTest.aspx

**Comment by isidore** [comment]
This is in: 
```xml
<PropertyGroup>
</PropertyGroup>
```
