### ISSUE TITLE
VisualStudioReporter incorrect comparison order of approved and received?

### ISSUE THREAD

**Issue by MihailsKuzmins** [approvals/ApprovalTests.Net#549]
When files are compared by the `VisualStudioReporter` "approved.json" is displayed on the right-hand side and "reveived.json" is displayed on the left-hand side. For it this order is a **very** misleading because in git a new file (i.e. "reveicied.json") is shown on the right-hand side.
So the current implementation of ApprovalTests makes me think that "approved.json" is the latest received file. Please consider this image.
When I look at this image I think that the latest file has a new field "Version". HOWEVER, actually the situation is the opposite. The field "Version" has been removed in the latest file. That's why I consider this implementation very confusing.
![image](https://user-images.githubusercontent.com/47413092/128057882-5d6f0995-74dc-41ac-8a7c-416a20c44859.png)

Apparently this method needs to be overridden in `VisualStudioReporter.cs`. If you agree that it could be a good improvement I could also try to prepare a PR for it.
https://github.com/approvals/ApprovalTests.Net/blob/443565ab7854eacf4bb455b3643688066c50d62e/src/ApprovalTests/Reporters/DiffToolReporter.cs#L15-L18

**Comment by SimonCropp** [comment]
@MihailsKuzmins 

changing `DiffRunner.Launch(diffTool, received, approved);` wont work  `DiffRunner.Launch` has logic in it that assumes the received and approved are passed in in the correct order. 

If you want to change this, it should be a PR in https://github.com/VerifyTests/DiffEngine that inverts the display order via an environment setting

**Comment by MihailsKuzmins** [comment]
@SimonCropp, thank you that you corrected my mistake of the design.
So as I understood `VisualStudio.cs` must be changed, to be more specific this line `(temp, target) => $"/diff \"{temp}\" \"{target}\"",`, where `temp` is "approved.json" and `target` is "received.json"
Running `Tools.DifFiles "received.json" "approved.json"` produced the result I had expected.

So I made this change and my test produced the result I had expected. If you think that this change is all right, I will create a PR for the [DiffEngine](https://github.com/VerifyTests/DiffEngine).
![image](https://user-images.githubusercontent.com/47413092/128243651-56904344-9bf2-4976-88fc-c8a00908d946.png)
![image](https://user-images.githubusercontent.com/47413092/128243541-b65506f6-dcbb-43e8-9619-aa6c3ff084a2.png)

**Comment by SimonCropp** [comment]
discussing on diffengine repo so will close this

**Comment by SimonCropp** [comment]
this can now be controlled using an environment variable https://github.com/VerifyTests/DiffEngine/blob/main/docs/diff-tool.md#leftright-diff-behavior

**Comment by MihailsKuzmins** [comment]
@SimonCropp,
thank you so much, your solution is more general and will cover similar cases in other reporters.
Tested the new version and it works as expected. Waiting for the new NuGet release
```cs
Environment.SetEnvironmentVariable("DiffEngine_TargetOnLeft", "true");
```

**Comment by SimonCropp** [comment]
the nuget is deployed. but note that you should not add `SetEnvironmentVariable("DiffEngine_TargetOnLeft` to your code
