### ISSUE TITLE
VerifyPdfFile failed at the random generated ID

### ISSUE THREAD

**Issue by michaelhuang1168** [approvals/ApprovalTests.Net#555]
It seems PDF files are generated with a unique ID (https://stackoverflow.com/questions/20085899/what-is-the-id-field-in-a-pdf-file)
even though the content and format of the 2 PDF I'm comparing are exactly the same, approval test is picking up the ID and fails the test.

Is there a way to scrub or ignore the ID?

I've attached the 2 PDF files below
[ClientInvoicePrintFeature.ClientInvoice_Jasper_Reprint_EPD_Attachment_ApprovalPDF.approved1.pdf](https://github.com/approvals/ApprovalTests.Net/files/7042866/ClientInvoicePrintFeature.ClientInvoice_Jasper_Reprint_EPD_Attachment_ApprovalPDF.approved1.pdf)
[ClientInvoicePrintFeature.ClientInvoice_Jasper_Reprint_EPD_Attachment_ApprovalPDF.approved.pdf](https://github.com/approvals/ApprovalTests.Net/files/7042867/ClientInvoicePrintFeature.ClientInvoice_Jasper_Reprint_EPD_Attachment_ApprovalPDF.approved.pdf)

**Comment by SimonCropp** [comment]
@michaelhuang1168 that software r u using to create your pdf?

**Comment by michaelhuang1168** [comment]
@SimonCropp that's right, the pdfs are created by our software

**Comment by SimonCropp** [comment]
yep. but what library are you using ?

**Comment by SimonCropp** [comment]
eg aspose?

**Comment by michaelhuang1168** [comment]
we are using JasperReports tp generate the PDF files

**Comment by SimonCropp** [comment]
This project is not being actively maintained. Instead consider using [Verify](https://github.com/VerifyTests/Verify/). See [Migrating from ApprovalTests](https://github.com/VerifyTests/Verify/blob/main/docs/compared-to-approvaltests.md#migrating-from-approvaltests) for more information.
