### ISSUE TITLE
Looking for VS 2022 support

### ISSUE THREAD

**Issue by bzuillsmith** [approvals/ApprovalTests.Net#562]
Hey there, just looking for VS 2022 support. Looks like DiffEngine now supports it but ApprovalTests is still on v6 of DiffEngine and DiffEngine is now v8. Is this planned or in the works at all?

**Comment by SimonCropp** [comment]
this is now deployed.

BTW if you want to use something that is more actively developed, try Verify https://github.com/VerifyTests/Verify

**Comment by bzuillsmith** [comment]
Blazingly fast, thank you! Interesting about Verify. Is the primary difference that it is under the .NET foundation? Otherwise why the different library?

**Comment by SimonCropp** [comment]
i wanted to start something new and from scratch using what i had learned from ApprovalTests. It wasnt productive to evolve ApprovalTests into the "something new". here are a few of the differences https://github.com/VerifyTests/Verify/blob/main/docs/compared-to-approvaltests.md

**Comment by my-nihongo** [comment]
@SimonCropp, could you please update the DiffEngine NuGet (https://github.com/approvals/ApprovalTests.Net/pull/597)?
With the current NuGet version only the preview of VS 2022 works. Standard versions of VS 2022 are ignored.

Here is the screen from the decompiled 5.7.1 NuGet version of ApprovalTests
![image](https://user-images.githubusercontent.com/65362546/154839258-4c0906f5-283b-4a9f-a6f6-0ef6815e02a1.png)

**Comment by MihailsKuzmins** [comment]
@SimonCropp, could you please update the DiffEngine NuGet (https://github.com/approvals/ApprovalTests.Net/pull/597)?
With the current NuGet version only the preview of VS 2022 works. Standard versions of VS 2022 are ignored.

Here is the screen from the decompiled 5.7.1 NuGet version of ApprovalTests
![image](https://user-images.githubusercontent.com/65362546/154839258-4c0906f5-283b-4a9f-a6f6-0ef6815e02a1.png)

**Comment by SimonCropp** [comment]
@MihailsKuzmins can u try ApprovalTests.5.7.2. but i recommend you move to Verify in the long term

**Comment by MihailsKuzmins** [comment]
@SimonCropp, thank you, it works.

Regarding Verify, I saw this post https://github.com/VerifyTests/Verify/blob/main/docs/compared-to-approvaltests.md, but decided to stick to ApprovalTests for the time being. Maybe I should change my mind and migrate all tests to Verify
