### ISSUE TITLE
Any documentation how to use ApprovalTests with Specflow?

### ISSUE THREAD

**Issue by dfibuch** [approvals/ApprovalTests.Net#580]
I apologise in advance if this has been covered somewhere, I did look. I want to use ApprovalTests in one of my `steps` of my integration test, to verify the XML we are generating is correct.

I've added the package to my project, added the reporter attribute and a single line of code:

`Approvals.VerifyXml(myXml);`

However, it is not showing me the diff tool and just errors with:

`ApprovalTests.Core.Exceptions.ApprovalMissingException : Failed Approval: Approval File "/workspace/tests/IntegrationTest.approved.xml" Not Found.`

It seems to be generating the `.received.xml` file.

Do I need to somehow force the diff tool to show up? I am using `Specflow.xUnit` to run the tests with a simple `dotnet test` command, which should be defaulting to run them in `Debug` mode.

**Comment by SimonCropp** [comment]
This project is not being actively maintained. Instead consider using [Verify](https://github.com/VerifyTests/Verify/). See [Migrating from ApprovalTests](https://github.com/VerifyTests/Verify/blob/main/docs/compared-to-approvaltests.md#migrating-from-approvaltests) for more information.

**Comment by dfibuch** [comment]
Thanks @SimonCropp . I'll close the question.
