### ISSUE TITLE
404 Errors from dead links in help document

### ISSUE THREAD

**Issue by csharpforevermore** [approvals/ApprovalTests.Net#608]
The  URL http://blog.approvaltests.com/2011/12/using-reporters-in-approval-tests.html is not working but is mentioned in the files

### Files affected
* [IntroductionReporter.cs](https://github.com/approvals/ApprovalTests.Net/blob/master/src/ApprovalTests/Reporters/IntroductionReporter.cs)
* [IntroductionReporterTest.TestComment.approved.txt](https://github.com/approvals/ApprovalTests.Net/blob/master/src/ApprovalTests.Tests/Reporters/IntroductionReporterTest.TestComment.approved.txt)

### Expected behaviour
Help documentation should be displayed when clicking the link (which appears when not adding the Reporter Attribute  to a test class)

### Actual behaviour
A 404 error message is displayed from Google docs.

**Comment by SimonCropp** [comment]
This project is not being actively maintained. Instead consider using [Verify](https://github.com/VerifyTests/Verify/). See [Migrating from ApprovalTests](https://github.com/VerifyTests/Verify/blob/main/docs/compared-to-approvaltests.md#migrating-from-approvaltests) for more information.
