### ISSUE TITLE
The compare appear to be in wrong order

### ISSUE THREAD

**Issue by notes2c** [approvals/ApprovalTests.Net#634]
Hi

When using [UseReporter(typeof(VisualStudioReporter))] and Visual Studio 2022 shows the diff window the files compared seems to be in wrong order

**Comment by SimonCropp** [comment]
can u share a screenshot

**Comment by notes2c** [comment]
When looking at the screenshot the static part (approved) is on the right side and the changed part (received) is on the left side.

I my opinion it should be the other way around. Apporved on the left side and received on the right side. That is also how VS is doing it.
![2022-09-26 16_33_36-Clipboard](https://user-images.githubusercontent.com/290553/192308952-e348fc03-4a96-40f5-992f-41eb767a85db.png)
![2022-09-26 16_48_05-Clipboard](https://user-images.githubusercontent.com/290553/192309078-b7935e3f-a7b8-4482-8574-c2621de012ba.png)

**Comment by SimonCropp** [comment]
u can change the behavior here https://github.com/VerifyTests/DiffEngine/blob/main/docs/diff-tool.md#leftright-diff-behavior
