### ISSUE TITLE
DiffEngine.ProcessCleanup throws System.TypeInitializationException when running failing test

### ISSUE THREAD

**Issue by NormanLie64** [approvals/ApprovalTests.Net#638]
No problem prior to latest Windows update. 
Using Visual Studio 2022
Approvaltests 5.7.3

Windows version now running:
Versjon	Windows 10 Pro
Versjon	21H2
Installert den	‎12.‎03.‎2021
Operativsystembygg	19044.2130
Opplevelse	Windows Feature Experience Pack 120.2212.4180.0

Error log from test:
Message: 
System.TypeInitializationException : Typeinitialiseringen for DiffEngine.ProcessCleanup forårsaket et unntak.
  ----> System.Management.ManagementException : Invalid class 

  Stack Trace: 
ProcessCleanup.TryGetProcessInfo(String command, ProcessCommand& process)
DiffRunner.InnerLaunch(TryResolveTool tryResolveTool, String tempFile, String targetFile) line 108
DiffRunner.Launch(String tempFile, String targetFile) line 43
DiffReporter.Report(String approved, String received) line 14
FileApprover.ReportFailure(IApprovalFailureReporter reporter) line 65
Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) line 13
Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) line 71
Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) line 52
Approvals.Verify(IApprovalWriter writer) line 124
Approvals.VerifyWithExtension(String text, String fileExtensionWithDot, Func`2 scrubber) line 189
Approvals.Verify(String text, Func`2 scrubber) line 176
ApprovalTests1.CreatedIntrumAssignmentsIsCorrect() line 85
--ManagementException
ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
ManagementObjectEnumerator.MoveNext()
<FindAll>d__3.MoveNext() line 38
List`1.ctor(IEnumerable`1 collection)
Enumerable.ToList[TSource](IEnumerable`1 source)
ProcessCleanup.Refresh() line 36
ProcessCleanup.cctor() line 30

**Comment by SimonCropp** [comment]
dup of https://github.com/VerifyTests/DiffEngine/issues/300
