### ISSUE TITLE
Api documentation seems to be missing

### ISSUE THREAD

**Issue by EamonNerbonne** [approvals/ApprovalTests.Net#88]
In the process of trying to use approvalstests I stumbled over the fact that usage outside of the simple model mentioned in the readme seems to be undocumented.  Given the wealth of information in podcasts+videos; perhaps there's just some link missing?

**Comment by SimonCropp** [comment]
docs has been improved over the last few year. so closing this. if u have specific feedback please raise a new issue

**Comment by EamonNerbonne** [comment]
Wow, that's been a while indeed!  If I find anything problematic, I'll post a new issue
