### ISSUE TITLE
Use of PerformanceCounter to retrieve process id triggers an infinite loop in MSTest when certain registry values are missing

### ISSUE THREAD

**Issue by kharabasz** [approvals/ApprovalTests.Net#90]
This issue affects the following reporters:
[TfsReporter](https://github.com/approvals/ApprovalTests.Net/blob/ad3d05cde410ee7ebf8621c20db73941c4948a4b/ApprovalTests/Reporters/TfsReporter.cs)
[VisualStudioCompareReporter](https://github.com/approvals/ApprovalTests.Net/blob/803f3845a9a86aa2a85159de9e749cd5d545c317/ApprovalTests/Reporters/VisualStudioCompareReporter.cs)
[VisualStudioReporter](https://github.com/approvals/ApprovalTests.Net/blob/ad3d05cde410ee7ebf8621c20db73941c4948a4b/ApprovalTests/Reporters/VisualStudioReporter.cs)

The following code...

```
var pc = new PerformanceCounter("Process", "Creating Process Id", 
    currentProcess.ProcessName);
return Process.GetProcessById((int)pc.RawValue);
```

...has an undocumented side effect during assembly loads (at least when being loaded by the MSTest runner), mainly calls to ntdll.dll/RegQueryValue for **_“HKLM\SOFTWARE\MICROSOFT\WINDOWS NT\CURRENTVERSION\PERFLIB\Disable Performance Counters”**_ and **_“HKLM\System\CurrentControlSet\Services\Process\Performance”**_.

The bug/quirk manifests when those registry keys are missing and the calls return **_"NAME NOT FOUND"**_. The assembly loader in MSTest does not fail, instead it enters an infinite loop, trying in vain to load said keys. This blocks tests from running and also causes a memory leak in the runner.

Due to the runners' verbosity, this behavior is not readily apparent. Below is the standard output from the runner - in the case of this behavior, the output never reaches the "Starting execution..." line.
- [x] Microsoft (R) Test Execution Command Line Tool Version 10.0.30319.1
- [x] Copyright (c) Microsoft Corporation. All rights reserved.
- [x] 
- [x] Loading C:...\Local.testsettings...
- [x] Loading C:...\TestAssemblyUsingApprovalTests.dll...
- [ ] Starting execution...
- [ ] 
- [ ] Results               Top Level Tests
- [ ]  -------               ---------------

The behavior was verifed using the [Sysinternals Process Monitor tool](http://technet.microsoft.com/en-us/sysinternals/bb896645)

I am not sure about the context, but would it be possible to pull this code out into a utility class and substitute the use of PerformanceCounter w/ something like p/invoke as in this [StackOverflow Question on retrieving a parent process id](http://stackoverflow.com/questions/394816/how-to-get-parent-process-in-net-in-managed-way) ?

**Comment by SimonCropp** [comment]
PerformanceCounters are no longer used to get the process name
