### ISSUE TITLE
Improve NUnit parser

### ISSUE THREAD

**Issue by GeertvanHorrik** [approvals/ApprovalTests.Net#93]
The parser currently forces the user to use the _Test_ attribute and does not allow to use the _TestCase_ attribute.

**Comment by KoHHeKT** [comment]
In that case approval files will have the same names for both TestCase attributes

**Comment by esperantos** [comment]
You can use NUnit.Framework.TestContext.CurrentContext.Test.Name in filename. But TeamCity will fail to run such test because it's test runner doesn't provide TestContext.

**Comment by GeertvanHorrik** [comment]
Note that this prevents this error;

```
System.Exception : 
Could Not Detect Test Framework

Either:
1) Optimizer Inlined Test Methods

Solutions:
a) Add [MethodImpl(MethodImplOptions.NoInlining)]
b) Set Build->Optimize Code to False
   & Build->Advanced->DebugInfo to Full

or
2) Approvals is not set up to use your test framework.
It currently supports [NUnit, MsTest, MbUnit, xUnit.net, xUnit.extensions, xUnit2.net, Machine.Specifications (MSpec)]

Solution:
To add one use ApprovalTests.Namers.StackTraceParsers.StackTraceParser.AddParser() method to add implementation of ApprovalTests.Namers.StackTraceParsers.IStackTraceParser with support for your testing framework.
To learn how to implement one see http://blog.approvaltests.com/2012/01/creating-namers.html
```

Hopefully this will show up in my search results next time I have this issue so I won't lose any time next time it happens to me :-)

**Comment by jawn** [comment]
The `NamerFactory.AdditionalInformation = caseName` approach works for me.

However, it seems that a block `using (ApprovalResults.ForScenario(s)) { testcode }` does the same.

Is there a reason to prefer one over the other?

**Comment by jawn** [comment]
Would there be a technical solution to remove the need for for any of the hacks below, and make it work right out of the box as expected?

> The `NamerFactory.AdditionalInformation = caseName` approach works for me.
> 
> However, it seems that a block `using (ApprovalResults.ForScenario(s)) { testcode }` does the same.
> 
> Is there a reason to prefer one over the other?

**Comment by SimonCropp** [comment]
given this was 6 years i assume u have on. so will close. please let us know if u still need this
